### ISSUE TITLE
Template ci is out of date

### ISSUE THREAD

**Issue by ruben-iteng** [atopile/atopile#774]
### Current Behaviour

`atopile-kicad` is out of date and can’t build `0.3.0`

### Expected Behaviour

CI exited with all checks "ok"

### Possible Solution

[project-template #13](https://github.com/atopile/project-template/pull/13)

### Version

0.3.3-dev

### Relevant log output

```shell
..Version mismatch..
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mawildoer** [comment]
This will be fixed upon release. As a temporary measure, you can tell the container to use `main` like this: 

```yaml
jobs:
  build:
    # ...

    steps:
      # ...

      - name: Build
        uses: docker://ghcr.io/atopile/atopile-kicad:main
```
